In [24]:
import pymongo
import pandas as pd

data_mongo= pymongo.MongoClient('localhost:27017')

db= data_mongo['test']

In [25]:
def mongo_data(collection):
    mongoColle= db[collection]
    data= list(mongoColle.find())
    df= pd.json_normalize(data,sep='_')
    df._id=df._id.astype(str)
    return df

In [26]:
df_animal=mongo_data('animals')
df_devis= mongo_data('devices')
df_plot= mongo_data('plots')
df_setith= mongo_data('settlementithcounts')
df_setle= mongo_data('settlements')

In [27]:
df_devis.deviceType.unique()#shape

array(['CARAVANA', 'COLLAR', 'PUNTO FIJO'], dtype=object)

In [28]:
df_plot['latitud']=df_plot.geoPoints.apply(lambda x: x[0]['lat'])
df_plot['longitud']=df_plot.geoPoints.apply(lambda x: x[0]['lng'])
df_plot['id_geoPoint']=df_plot.geoPoints.apply(lambda x: x[0]['_id'] if '_id' in x[0] else None)

In [29]:
df_setle['id_limits']=df_setle.limits.apply(lambda x: x[0]['_id'] if len(x)>0 else None )
df_setle['latitud']=df_setle.limits.apply(lambda x: x[0]['lat'] if len(x)>0 else None )
df_setle['longitud']=df_setle.limits.apply(lambda x: x[0]['lng'] if len(x)>0 else None )

In [35]:
df_setle[df_setle._id=='620e6e5e60543d0026a01f0e']

,_id,enabledUsers,plots,limits,hectares,registerNumber,headsCount,name,createdAt,updatedAt,__v,centralPoint,auravantApiKey,enabled,id_limits,latitud,longitud
0,620e6e5e60543d0026a01f0e,"[6201245070900d002592d7ec, 636c17ea2bd5b200305...","[63b55f4b973f9f35c0c5b37d, 63b55f4b973f9f35c0c...","[{'_id': 63cedb56ea0de8476c39744d, 'lat': -32....",5000.0,XCSS12345,10.0,La Florida,2022-02-17 15:48:47.058,2023-02-17 15:11:39.739,0,"[{'_id': 63cedb56ea0de8476c397457, 'lat': -32....",eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzcmMiO...,True,63cedb56ea0de8476c39744d,-32.852009,-63.641726

In [32]:
df_devis[df_devis.deviceMACAddress=='BC27B1A003FE']

,_id,deviceType,deviceFirmwareVersion,deviceMACAddress,deviceAnimalID,__v
0,62d56cc2e71f68426833cc74,CARAVANA,2222,BC27B1A003FE,640f6ef10c8f4c1edc6767e4,0

In [31]:
df_devis[df_devis.deviceType=='COLLAR']

,_id,deviceType,deviceFirmwareVersion,deviceMACAddress,deviceAnimalID,__v
8,62f52bee401c510025e01f29,COLLAR,2.0.0,0004A30B00F82BD2,62d6e9920408c608acb6fdd0,0
29,62f52cd3401c510025e01f60,COLLAR,2.0.0,0004A30B00EE959D,62d6ea330408c608acb6fe4e,0
35,638660af3039cf00301d200d,COLLAR,2222,0004A30B00F825B7,638660af3039cf00301d200e,0
37,638f7f2f3feed4114c00428b,COLLAR,2222,22222,62d98f17a30a66002645c2ff,0
41,63ee8291476a9d0030806795,COLLAR,2.2.03,C98BB10944DE,640f6ef10c8f4c1edc67680d,0
42,63f66d0cd3575e0030304d6d,COLLAR,2.1.0,11111111111,63f66cc4d3575e0030304d2c,0
142,63ed134ca9f1a40025795ea5,COLLAR,2.1.0,0004A30B00F8A181,63ed1054a9f1a40025795708,0
143,63ed138fa9f1a40025795eb1,COLLAR,2.1.0,0004A30B00F869B4,63ed0d7ca9f1a400257942d7,0
144,63ed13d9a9f1a40025795ec7,COLLAR,2.1.0,0004A30B00F82E81,63ed0e71a9f1a40025794898,0
145,63ed13f6a9f1a40025795edd,COLLAR,2.1.0,0004A30B00F841E4,63ed0eb2a9f1a40025794ac8,0
146,63ed1494a9f1a40025795f0b,COLLAR,2.1.0,0004A30B00F8B356,63ed0ddca9f1a400257944c0,0
154,63fcff17db53680da4769d3a,COLLAR,1010,10101010,63ee8200476a9d00308065fb,0
161,640f1bc3fd164103dc37fd68,COLLAR,11111,11111,640095b298dd6400309d7bfb,0
162,640f3287fd164103dc37feb4,COLLAR,131313,51588585,63efe06ce429423750fcbb31,0
163,640f37df4476f62638c7adbe,COLLAR,121212,12121222,640095b298dd6400309d7bfd,0
561,64235e6e62f1a32bd8fff5fb,COLLAR,2200,0004A30B00F89C52,64235c730dac550030135fa4,0
562,64235e6e62f1a32bd8fff5ff,COLLAR,2200,0004A30B00F81069,64235c730dac550030135fac,0
563,64235e6e62f1a32bd8fff603,COLLAR,2200,0004A30B00F7E0C6,64235c730dac550030135fae,0
564,64235e6e62f1a32bd8fff60f,COLLAR,2200,0004A30B00F83085,64235c730dac550030135fb4,0
565,64235e6e62f1a32bd8fff611,COLLAR,2200,0004A30B00F840D6,64235c730dac550030135fb2,0
566,642360b02db4a76760913a53,COLLAR,2200,0004A30B00F842B6,64235c730dac550030135fa7,0
567,642360b02db4a76760913a5a,COLLAR,2200,0004A30B00F8B217,64235c730dac550030135fb0,0
568,642360b02db4a76760913a58,COLLAR,2200,0004A30B00F81075,64235c730dac550030135faa,0
569,64236c77cf291b10b4ea5575,COLLAR,2200,0004A30B00F862AF,642367fd0dac550030136043,0
570,64236c77cf291b10b4ea557a,COLLAR,2200,0004A30B00F82EB9,642367fd0dac550030136047,0
571,64236c77cf291b10b4ea557c,COLLAR,2200,0004A30B00F842C1,642367fd0dac550030136045,0

In [30]:
df_setle['id_central']=df_setle.centralPoint.apply(lambda x: x[0]['_id'] if '_id' in x[0] else None)
df_setle['latitud_c']=df_setle.centralPoint.apply(lambda x: x[0]['lat'] if 'lat' in x[0] else None)
df_setle['longitud_c']=df_setle.centralPoint.apply(lambda x: x[0]['lng'] if 'lng' in x[0] else None)

In [32]:
df_devis[df_devis.deviceMACAddress=='4DF83DE59CD8']

,_id,deviceType,deviceFirmwareVersion,deviceMACAddress,deviceAnimalID,__v
84,63ed0e73a9f1a400257948ab,CARAVANA,2.2.0,4DF83DE59CD8,63ed0e73a9f1a400257948a6,0